version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oauthDB
    ports:
      - 5432:5432
    volumes:
      - oauthdb:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    volumes:
      - redis_data:/data

volumes:
  oauthdb:
  redis_data:
